title: Zero to Data 8
author: UC Berkeley Division of Computing, Data Science, and Information
logo: content/data8.png
exclude_patterns: ["content/v1/deploy/scripts/tests"]
html:
  baseurl: zero-to-data-8 # the subpath of your site, e.g. /blog. If there is no subpath for your site, use an empty string ""
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

repository:
  url: https://github.com/data-8/zero-to-data-8

